# Generated by Django 4.1.3 on 2023-05-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='context',
            field=models.BinaryField(),
        ),
    ]
