# Generated by Django 4.1.3 on 2023-05-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chat_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='response',
            field=models.BinaryField(),
        ),
    ]
